services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: vehicleguard
      POSTGRES_USER: vg_user
      POSTGRES_PASSWORD: vg_local_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data

volumes:
  postgres_data:
  mosquitto_data:
